apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
  namespace: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: member-api
          image: ghcr.io/nhn-academy-marco/member-api:bd737b4ca9ec8cf891d59f12aac9d6f8f53ac6d1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"